Analyzing Data with Python 
NUMPY
 


Q.1 Convert a 1D array to a 2D array with 2 rows 

In [1]:
import numpy as np

data = np.array([1,2,3,4,5,6])

reshape_array = data.reshape(2,-1)

print(reshape_array)


[[1 2 3]
 [4 5 6]]


Q.2

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common = np.intersect1d(a,b)

print(common)

[2 4]


Q.3



In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

new_arr = a[(a>=5)&(a<=10)]

print(new_arr)


[ 6  9 10]


Q.4

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

np.set_printoptions(threshold=6)

print(a)

[ 0  1  2 ... 12 13 14]


1. Compute the minimum, 25th percentile, median, 75th, and maximum of ser.



In [ ]:
import numpy as np

ser = np.array([12, 7, 22, 15, 9, 31, 18, 25, 13, 17])

minimum =np.min(ser)
percentile_25 = np.percentile(ser,25)
median = np.median(ser)
percentile_75 = np.percentile(ser,75)
maximum = np.max(ser)

# Print the results
print(f"Minimum: {minimum}")
print(f"25th Percentile: {percentile_25}")
print(f"Median: {median}")
print(f"75th Percentile: {percentile_75}")
print(f"Maximum: {maximum}")


Minimum: 7
25th Percentile: 12.25
Median: 16.0
75th Percentile: 21.0
Maximum: 31


2. Creating A Pandas Data Frame and Using Sample Data Sets


In [2]:
import pandas as pd

data = {
    "Name": ["soham", "raj", "ved", "krish"],
    "Age": [25, 30, 35, 40],
    "City": ["gandhinagar", "mansa", "rajkot", "bharuch"]
}

df = pd.DataFrame(data)


print(df)


    Name  Age         City
0  soham   25  gandhinagar
1    raj   30        mansa
2    ved   35       rajkot
3  krish   40      bharuch


3.Using NumPy, create a Pandas Data Frame with five rows and three columns.

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

print(df)


          A         B         C
0  0.668499 -0.979527  1.071846
1 -1.521101 -0.545291  0.219980
2  0.352217 -1.080472 -1.361429
3  0.322467  1.584726  2.051178
4  0.546294  1.813314  0.264355


4.When you create a Pandas DataFrame from a NumPy array without specifying labels, Pandas assigns default integer-based labels for both rows and columns.

Default Behavior:
Rows (Index): Labeled with integers starting from 0 (e.g., 0, 1, 2, ...).
Columns: Also labeled with integers starting from 0 (e.g., 0, 1, 2, ...).

6.Write the code to show the number of rows and columns in data frame

In [ ]:
import pandas as pd

df = pd.read_csv("file_name.csv")

rows, cols = df.shape

print(f"Number of Rows: {rows}")
print(f"Number of Columns: {cols}")


7.How might you show the first few rows of data frame?

In [ ]:
import pandas as pd

df = pd.read_csv("file_name.csv")

print(df.head())
# we can customize them to multiple rows 
print(df.head(20))

8. If you select a single column from the diamonds Data Frame, what will be the type of the
return value?

In [ ]:
import pandas as pd

df = pd.read_csv("diamonds.csv")  

carat_series = df["carat"]

print(type(carat_series))  


13.Key Features of TensorFlow --> 
Open-Source & Scalable – Free, supports small to large-scale ML models.
Multi-Language Support – Works with Python, C++, JavaScript, Swift, Java, Go.
GPU & TPU Acceleration – Fast training with hardware acceleration.
High & Low-Level APIs – Keras (easy) & Low-level API (flexible).
Automatic Differentiation – Computes gradients for optimization.
TensorFlow Lite – Runs ML models on mobile & IoT devices.
TensorFlow.js – ML models in the browser.
TensorBoard – Interactive visualization of models & training.
Distributed Training – Train on multiple GPUs & TPUs.
Pre-trained Models – Use Inception, ResNet, BERT, YOLO, etc.
Integration – Works with NumPy, Pandas, OpenCV, Scikit-learn.
Deployment Ready – Supports Cloud, Mobile, Web, Embedded AI.

14.Limitations of TensorFlow--> 
Steep Learning Curve – Complex syntax, especially for beginners.
Difficult Debugging – Hard to track errors in large models.
Slow Compilation – Training can be slower compared to PyTorch in some cases.
Memory Consumption – High RAM usage, especially for large models.
Static Graph Execution – TensorFlow 1.x required defining the computation graph before execution (fixed in TF 2.x with eager execution).
Limited Mobile Support – TensorFlow Lite lacks some advanced ML features.
Less Flexibility – Compared to PyTorch, modifying models dynamically is harder.
GPU Dependency – Requires NVIDIA CUDA for GPU acceleration, limiting AMD GPU support.
Large File Size – Trained models can be heavy and require optimization.
Inconsistent Documentation – Some features have outdated or insufficient documentation.

15.
Supervised Learning 
Definition:
Supervised learning is a machine learning technique where a model is trained on labeled data (input-output pairs). The model learns the relationship between inputs (features) and outputs (labels) to make predictions on new data.

Unsupervised Learning 
Definition:
Unsupervised learning is a machine learning technique where a model learns patterns and structures from unlabeled data (data without predefined categories or labels).